#====================================
#              変数
#====================================

# @baseurl = https://challenge-your-limits.herokuapp.com
@baseurl = http://localhost:8000/api/q01
@name = sample_02
@invalid_email = sample_02
@already_taken_email = foo@gmail.com
@valid_email = sample_02@gmail.com

#====================================
#
#====================================

GET {{baseurl}}/call/me?param1=val1

###
POST {{baseurl}}/call/me

###

GET {{baseurl}}/challenge_users

###

POST {{baseurl}}/challenge_users

###

POST {{baseurl}}/challenge_users
content-type: application/json

{
    "name": "{{name}}"
}


###

POST {{baseurl}}/challenge_users
content-type: application/json

{
    "name": "{{name}}",
    "email": "{{invalid_email}}"
}


###

POST {{baseurl}}/challenge_users
content-type: application/json

{
    "name": "{{name}}",
    "email": "{{already_taken_email}}"
}


###

POST {{baseurl}}/challenge_users
content-type: application/json

{
    "name": "{{name}}",
    "email": "{{valid_email}}"
}

