#====================================
#              変数
#====================================

# @baseurl = https://challenge-your-limits.herokuapp.com
@baseurl = http://localhost:8000/api

#====================================
#　        Sample Action
#====================================

### Action - index
GET {{baseurl}}/sample/
content-type: application/json

{
    "limit": "1"
}

### Action - create
GET {{baseurl}}/sample/create/

### Action - store
POST {{baseurl}}/sample/store/
content-type: application/json

{
    "name": "StoredSampleName"
}

### Action - show
GET {{baseurl}}/sample/show/
content-type: application/json

{
    "name": "SampleName01"
}

### Action - edit
GET {{baseurl}}/sample/edit/

### Action - update
PUT {{baseurl}}/sample/update/
content-type: application/json

{
    "id": "1",
    "name": "UpdatedName"
}

### Action - destroy
DELETE {{baseurl}}/sample/destroy/
content-type: application/json

{
    "id": "2"
}

### Action - delete
DELETE {{baseurl}}/sample/delete/
content-type: application/json

{
    "id": "2"
}
